quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

%dev.quarkus.datasource.devservices.image-name=postgres:17-alpine
%test.quarkus.datasource.devservices.image-name=postgres:17-alpine

%prod.quarkus.datasource.jdbc.url=${BOMFILME_DB_URL}
%prod.quarkus.datasource.username=${BOMFILME_DB_USER}
%prod.quarkus.datasource.password=${BOMFILME_DB_PASSWORD}
